export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_ERROR = 'LOGIN_START_ERROR';
export const CERRAR_LOGIN_SUCCESS = 'CERRAR_LOGIN_SUCCESS';
